/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat Oct 18 18:57:08 2025
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


